name: Send daily prompt

on:
  schedule:
    - cron: "0 12 * * *"  # каждый день в 8:00 UTC
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          with:
          python-version: '3.10'
      - name: Установить зависимости
        run: pip install -r requirements.txt
      - name: Запустить скрипт
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
